const translations = {
    en: {
        "welcome_message": "Welcome to Professional Guidance!",
        "intro_paragraph": "Your one-stop solution for navigating your academic and career journey. Explore hobbies, colleges, exams, scholarships, and more.",
        "get_started": "Get Started",
        "copyright": "&copy; 2025 Professional Guidance. All rights reserved.",
        "professional_guidance": "Professional Guidance",
        // Features page
        "unlock_potential": "Unlock Your Potential with Our Key Features",
        "explore_hobbies_careers": "Explore Hobbies & Careers",
        "hobbies_careers_desc": "Discover how your passions can lead to a fulfilling career path. Our extensive database connects hobbies with real-world professions.",
        "learn_more": "Learn More",
        "top_colleges_courses": "Top Colleges & Courses",
        "colleges_courses_desc": "Browse detailed information on leading educational institutions and their diverse course offerings to find your perfect fit.",
        "find_colleges": "Find Colleges",
        "entrance_exam_prep": "Entrance Exam Prep",
        "exam_prep_desc": "Access comprehensive guides, practice tests, and essential resources to ace your entrance exams and secure admission.",
        "prepare_now": "Prepare Now",
        "scholarship_opportunities": "Scholarship Opportunities",
        "scholarship_desc": "Find and apply for various scholarships to fund your education. Don't let financial barriers stand in the way of your dreams.",
        "get_scholarships": "Get Scholarships",
        "aptitude_quiz": "Aptitude Quiz",
        "quiz_desc": "Take our interactive aptitude quiz to understand your strengths and discover suitable career paths aligned with your abilities.",
        "take_quiz": "Take Quiz",
        "personalized_roadmap": "Personalized Roadmap",
        "roadmap_desc": "Generate a customized educational and career roadmap tailored to your aspirations and academic profile. Plan your future effectively.",
        "create_roadmap": "Create Roadmap",
        "nep2020_insights": "NEP 2020 Insights",
        "nep2020_desc": "Understand the National Education Policy 2020 and its impact on your academic and career journey. Stay informed about the latest reforms.",
        "after_10th_grade": "After 10th Grade",
        "after_10th_desc": "Explore various academic streams and vocational courses available after completing 10th grade. Make informed decisions for your future.",
        "explore_options": "Explore Options",
        "personal_dashboard": "Personal Dashboard",
        "dashboard_desc": "View your personalized career insights, quiz results, and saved preferences in one convenient location.",
        "view_dashboard": "View Dashboard",
        // Scholarships page
        "scholarship_opportunities_heading": "Scholarship Opportunities",
        "scholarship_page_intro": "Find various scholarships to support your education.",
        "filter_by_type": "Filter by Type:",
        "all": "All",
        "central_government": "Central Government",
        "west_bengal_state": "West Bengal State",
        "maharashtra_state": "Maharashtra State",
        // Roadmap page
        "roadmap_heading": "Your Academic & Career Roadmap (Class 10 & 12)",
        "roadmap_intro": "Navigate your journey from school to college with these clear steps.",
        "class10_completion": "Class 10 Completion",
        "class10_desc": "Focus on your core subjects and identify your strengths and interests. Explore different streams available after Class 10.",
        "stream_choice_class11": "Stream Choice (Class 11)",
        "stream_choice_desc": "Choose a stream (Science, Commerce, Arts/Humanities) that aligns with your career aspirations and aptitude. Research future prospects for each stream.",
        "class12_prep_exams": "Class 12 Preparation & Entrance Exams",
        "class12_prep_desc": "Dedicate yourself to Class 12 studies. Identify relevant entrance exams (e.g., JEE, NEET, CLAT) for your chosen career path and begin preparation.",
        "college_course_selection": "College & Course Selection",
        "college_course_desc": "Research top colleges and courses based on your stream and entrance exam performance. Consider factors like faculty, infrastructure, placements, and fees.",
        "admissions_scholarships": "Admissions & Scholarships",
        "admissions_scholarships_desc": "Apply to your preferred colleges and courses. Explore various scholarship opportunities (government, private) to fund your education.",
        // Quiz page
        "aptitude_quiz_heading": "Aptitude Quiz",
        "quiz_intro": "Answer a few questions to get personalized insights into potential career paths.",
        "q1_text": "1. Which of these activities do you enjoy the most?",
        "q1_opt1": "Creative arts (writing, painting, music)",
        "q1_opt2": "Solving complex puzzles or logical problems",
        "q1_opt3": "Helping and interacting with people",
        "q2_text": "2. What kind of school subjects do you find most engaging?",
        "q2_opt1": "Science (Physics, Chemistry, Biology)",
        "q2_opt2": "Mathematics and problem-solving",
        "q2_opt3": "History, Literature, Social Sciences",
        "q3_text": "3. What's your ideal work environment?",
        "q3_opt1": "Independent work, self-directed projects",
        "q3_opt2": "Collaborative team-based projects",
        "q3_opt3": "Fast-paced, constantly changing environment",
        "get_my_results": "Get My Results",
        // NEP 2020 page
        "nep2020_heading": "National Education Policy 2020",
        "nep2020_page_intro": "The National Education Policy 2020 (NEP 2020) aims to transform India's education system to meet the demands of the 21st century. It focuses on holistic, flexible, and multidisciplinary education, moving away from rote learning to critical thinking and experiential learning.",
        "key_reforms": "Key Reforms:",
        "ecc_education": "Early Childhood Care and Education (ECCE) from age 3.",
        "new_curricular_structure": "New 5+3+3+4 curricular structure.",
        "no_rigid_separation": "No rigid separation between arts and sciences, curricular and extra-curricular activities, vocational and academic streams.",
        "foundational_literacy_numeracy": "Emphasis on foundational literacy and numeracy.",
        "vocational_digital_learning": "Increased focus on vocational education and digital learning.",
        "national_research_foundation": "Establishment of a National Research Foundation.",
        "more_info": "For more detailed information, please visit the official Ministry of Education website:",
        "official_nep2020_link": "Official NEP 2020 Link",
        // Hobby page
        "hobby_suggestions_heading": "Hobby to Career Suggestions",
        "hobby_page_intro": "Discover career paths that align with your passions!",
        // Exams page
        "key_entrance_exams_heading": "Key Entrance Exams",
        "exams_page_intro": "Find important entrance exams for various streams.",
        "filter_by_stream": "Filter by Stream:",
        "engineering": "Engineering",
        "medical": "Medical",
        "law": "Law",
        "arts": "Arts",
        "degree": "Degree",
        // Dashboard page
        "personal_dashboard_heading": "Your Personal Dashboard",
        "dashboard_page_intro": "Welcome to your personalized career insights!",
        "your_selections": "Your Selections:",
        "preferred_stream": "Preferred Stream:",
        "interests": "Interests:",
        "clear_my_data": "Clear My Data",
        // Colleges page
        "top_govt_colleges_heading": "Top Government Colleges",
        "colleges_page_intro": "Explore leading government colleges across various streams.",
        // After 10th page
        "subject_choices_10th_heading": "Subject Choices After 10th Grade",
        "subject_choices_10th_intro": "Choosing the right stream after 10th grade is crucial for your career path. Explore the options and what they entail.",
        "science_stream": "Science Stream",
        "science_focus": "Focus: Physics, Chemistry, Biology/Math",
        "science_careers": "Career Paths: Engineering, Medicine, Research, IT",
        "science_skills": "Key Skills: Analytical thinking, problem-solving, logical reasoning",
        "commerce_stream": "Commerce Stream",
        "commerce_focus": "Focus: Accountancy, Business Studies, Economics, Math",
        "commerce_careers": "Career Paths: Finance, Accounting, Business Management, Marketing",
        "commerce_skills": "Key Skills: Financial literacy, organizational skills, critical thinking",
        "arts_humanities_stream": "Arts/Humanities Stream",
        "arts_focus": "Focus: History, Political Science, Geography, Psychology, Literature",
        "arts_careers": "Career Paths: Civil Services, Journalism, Law, Teaching, Design",
        "arts_skills": "Key Skills: Communication, creativity, critical analysis, research",
        "explore_polytechnic_courses": "Explore Polytechnic Courses",
        "polytechnic_intro": "Polytechnic courses offer hands-on training and direct entry into various technical careers after 10th or 12th grade.",
        "diploma_engineering": "Diploma in Engineering",
        "engineering_fields": "Fields: Mechanical, Civil, Electrical, Computer Science, Electronics",
        "engineering_eligibility": "Eligibility: 10th pass",
        "engineering_career": "Career: Junior Engineer, Technician roles",
        "view_details": "View Details",
        "diploma_business_admin": "Diploma in Business Administration",
        "business_fields": "Fields: Marketing, Finance, HR, Operations",
        "business_eligibility": "Eligibility: 10th/12th pass",
        "business_career": "Career: Business Analyst, Office Manager, Marketing Assistant",
        "diploma_hotel_management": "Diploma in Hotel Management",
        "hotel_fields": "Fields: Food & Beverage, Front Office, Housekeeping, Culinary Arts",
        "hotel_eligibility": "Eligibility: 10th/12th pass",
        "hotel_career": "Career: Hotel Operations, Chef, Event Management",
        "explore_vocational_courses": "Explore Vocational Courses",
        "vocational_intro": "Vocational courses provide practical skills for specific trades, offering direct entry into various industries after 10th grade.",
        "cert_electrician": "Certificate in Electrician",
        "electrician_duration": "Duration: 1 Year",
        "electrician_eligibility": "Eligibility: 10th Pass",
        "electrician_career": "Career: Electrician, Electrical Technician",
        "diploma_nanny_care": "Diploma in Nanny Care",
        "nanny_duration": "Duration: 2 Years",
        "nanny_eligibility": "Eligibility: 10th Pass",
        "nanny_career": "Career: Nanny, Childcare Professional",
        "diploma_automobile": "Diploma in Automobile",
        "automobile_duration": "Duration: 2 Years",
        "automobile_eligibility": "Eligibility: 10th Pass",
        "automobile_career": "Career: Automobile Technician, Service Advisor",
    },
    hi: {
        "welcome_message": "प्रोफेशनल गाइडेंस में आपका स्वागत है!",
        "intro_paragraph": "आपकी शैक्षिक और करियर यात्रा को नेविगेट करने के लिए आपका वन-स्टॉप समाधान। हॉबी, कॉलेज, परीक्षा, छात्रवृत्ति, और बहुत कुछ खोजें।",
        "get_started": "शुरू करें",
        "copyright": "&copy; 2025 प्रोफेशनल गाइडेंस। सर्वाधिकार सुरक्षित।",
        "professional_guidance": "प्रोफेशनल गाइडेंस",
        // Features page
        "unlock_potential": "हमारी मुख्य विशेषताओं के साथ अपनी क्षमता को अनलॉक करें",
        "explore_hobbies_careers": "शौक और करियर का अन्वेषण करें",
        "hobbies_careers_desc": "डिस्कवर करें कि आपके जुनून कैसे एक पूर्ण करियर पथ का नेतृत्व कर सकते हैं। हमारा व्यापक डेटाबेस शौक को वास्तविक दुनिया के व्यवसायों से जोड़ता है।",
        "learn_more": "और जानें",
        "top_colleges_courses": "शीर्ष कॉलेज और पाठ्यक्रम",
        "colleges_courses_desc": "अपने लिए सही विकल्प खोजने के लिए प्रमुख शिक्षण संस्थानों और उनके विविध पाठ्यक्रम प्रस्तावों के बारे में विस्तृत जानकारी ब्राउज़ करें।",
        "find_colleges": "कॉलेज ढूंढें",
        "entrance_exam_prep": "प्रवेश परीक्षा की तैयारी",
        "exam_prep_desc": "अपनी प्रवेश परीक्षाओं में सफल होने और प्रवेश सुरक्षित करने के लिए व्यापक गाइड, अभ्यास परीक्षण औरB आवश्यक संसाधनों तक पहुंचें।",
        "prepare_now": "अभी तैयारी करें",
        "scholarship_opportunities": "छात्रवृत्ति के अवसर",
        "scholarship_desc": "अपनी शिक्षा को वित्तपोषित करने के लिए विभिन्न छात्रवृत्तियों को खोजें और आवेदन करें। वित्तीय बाधाओं को अपने सपनों के रास्ते में न आने दें।",
        "get_scholarships": "छात्रवृत्ति प्राप्त करें",
        "aptitude_quiz": "योग्यता प्रश्नोत्तरी",
        "quiz_desc": "अपनी शक्तियों को समझने और अपनी क्षमताओं के अनुरूप उपयुक्त करियर पथों की खोज के लिए हमारी इंटरैक्टिव योग्यता प्रश्नोत्तरी लें।",
        "take_quiz": "प्रश्नोत्तरी लें",
        "personalized_roadmap": "व्यक्तिगत रोडमैप",
        "roadmap_desc": "अपनी आकांक्षाओं और अकादमिक प्रोफ़ाइल के अनुरूप एक अनुकूलित शैक्षिक और करियर रोडमैप तैयार करें। अपने भविष्य की प्रभावी ढंग से योजना बनाएं।",
        "create_roadmap": "रोडमैप बनाएं",
        "nep2020_insights": "एनईपी 2020 अंतर्दृष्टि",
        "nep2020_desc": "राष्ट्रीय शिक्षा नीति 2020 और आपकी अकादमिक और करियर यात्रा पर इसके प्रभाव को समझें। नवीनतम सुधारों के बारे में सूचित रहें।",
        "after_10th_grade": "10वीं कक्षा के बाद",
        "after_10th_desc": "10वीं कक्षा पूरी करने के बाद उपलब्ध विभिन्न अकादमिक धाराओं और व्यावसायिक पाठ्यक्रमों का अन्वेषण करें। अपने भविष्य के लिए सूचित निर्णय लें।",
        "explore_options": "विकल्प तलाशें",
        "personal_dashboard": "व्यक्तिगत डैशबोर्ड",
        "dashboard_desc": "अपने व्यक्तिगत करियर अंतर्दृष्टि, प्रश्नोत्तरी परिणाम और सहेजी गई वरीयताओं को एक सुविधाजनक स्थान पर देखें।",
        "view_dashboard": "डैशबोर्ड देखें",
        // Scholarships page
        "scholarship_opportunities_heading": "छात्रवृत्ति के अवसर",
        "scholarship_page_intro": "अपनी शिक्षा का समर्थन करने के लिए विभिन्न छात्रवृत्तियां खोजें।",
        "filter_by_type": "प्रकार से फ़िल्टर करें:",
        "all": "सभी",
        "central_government": "केंद्र सरकार",
        "west_bengal_state": "पश्चिम बंगाल राज्य",
        "maharashtra_state": "महाराष्ट्र राज्य",
        // Roadmap page
        "roadmap_heading": "आपका अकादमिक और करियर रोडमैप (कक्षा 10 और 12)",
        "roadmap_intro": "इन स्पष्ट चरणों के साथ स्कूल से कॉलेज तक अपनी यात्रा को नेविगेट करें।",
        "class10_completion": "कक्षा 10 पूर्णता",
        "class10_desc": "अपने मुख्य विषयों पर ध्यान केंद्रित करें और अपनी शक्तियों और रुचियों की पहचान करें। कक्षा 10 के बाद उपलब्ध विभिन्न धाराओं का अन्वेषण करें।",
        "stream_choice_class11": "स्ट्रीम विकल्प (कक्षा 11)",
        "stream_choice_desc": "एक स्ट्रीम (विज्ञान, वाणिज्य, कला/मानविकी) चुनें जो आपकी करियर आकांक्षाओं और योग्यता के साथ संरेखित हो। प्रत्येक स्ट्रीम के लिए भविष्य की संभावनाओं पर शोध करें।",
        "class12_prep_exams": "कक्षा 12 की तैयारी और प्रवेश परीक्षा",
        "class12_prep_desc": "कक्षा 12 के अध्ययन के लिए खुद को समर्पित करें। अपने चुने हुए करियर पथ के लिए प्रासंगिक प्रवेश परीक्षाओं (जैसे, जेईई, एनईईटी, सीएलएटी) की पहचान करें और तैयारी शुरू करें।",
        "college_course_selection": "कॉलेज और पाठ्यक्रम चयन",
        "college_course_desc": "अपनी स्ट्रीम और प्रवेश परीक्षा के प्रदर्शन के आधार पर शीर्ष कॉलेजों और पाठ्यक्रमों पर शोध करें। फैकल्टी, इन्फ्रास्ट्रक्चर, प्लेसमेंट और फीस जैसे कारकों पर विचार करें।",
        "admissions_scholarships": "प्रवेश और छात्रवृत्ति",
        "admissions_scholarships_desc": "अपने पसंदीदा कॉलेजों और पाठ्यक्रमों में आवेदन करें। अपनी शिक्षा को वित्तपोषित करने के लिए विभिन्न छात्रवृत्ति अवसरों (सरकारी, निजी) का अन्वेषण करें।",
        // Quiz page
        "aptitude_quiz_heading": "योग्यता प्रश्नोत्तरी",
        "quiz_intro": "संभावित करियर पथों में व्यक्तिगत अंतर्दृष्टि प्राप्त करने के लिए कुछ प्रश्नों के उत्तर दें।",
        "q1_text": "1. इनमें से कौन सी गतिविधि आपको सबसे अधिक पसंद है?",
        "q1_opt1": "रचनात्मक कला (लेखन, चित्रकला, संगीत)",
        "q1_opt2": "जटिल पहेलियों या तार्किक समस्याओं को हल करना",
        "q1_opt3": "लोगों की मदद करना और उनसे बातचीत करना",
        "q2_text": "2. आपको किस तरह के स्कूल विषय सबसे आकर्षक लगते हैं?",
        "q2_opt1": "विज्ञान (भौतिकी, रसायन विज्ञान, जीव विज्ञान)",
        "q2_opt2": "गणित और समस्या-समाधान",
        "q2_opt3": "इतिहास, साहित्य, सामाजिक विज्ञान",
        "q3_text": "3. आपका आदर्श कार्य वातावरण क्या है?",
        "q3_opt1": "स्वतंत्र कार्य, स्व-निर्देशित परियोजनाएं",
        "q3_opt2": "सहयोगी टीम-आधारित परियोजनाएं",
        "q3_opt3": "तेज-तर्रार, लगातार बदलता माहौल",
        "get_my_results": "मेरे परिणाम प्राप्त करें",
        // NEP 2020 page
        "nep2020_heading": "राष्ट्रीय शिक्षा नीति 2020",
        "nep2020_page_intro": "राष्ट्रीय शिक्षा नीति 2020 (एनईपी 2020) का उद्देश्य 21वीं सदी की मांगों को पूरा करने के लिए भारत की शिक्षा प्रणाली को बदलना है। यह रटने की बजाय आलोचनात्मक सोच और अनुभवात्मक सीखने पर ध्यान केंद्रित करते हुए समग्र, लचीली और बहु-विषयक शिक्षा पर केंद्रित है।",
        "key_reforms": "मुख्य सुधार:",
        "ecc_education": "3 साल की उम्र से प्रारंभिक बचपन की देखभाल और शिक्षा (ईसीसीई)।",
        "new_curricular_structure": "नई 5+3+3+4 पाठ्यचर्या संरचना।",
        "no_rigid_separation": "कला और विज्ञान, पाठ्यचर्या और अतिरिक्त पाठ्यचर्या गतिविधियों, व्यावसायिक और अकादमिक धाराओं के बीच कोई कठोर अलगाव नहीं।",
        "foundational_literacy_numeracy": "बुनियादी साक्षरता और संख्या ज्ञान पर जोर।",
        "vocational_digital_learning": "व्यावसायिक शिक्षा और डिजिटल सीखने पर अधिक ध्यान।",
        "national_research_foundation": "एक राष्ट्रीय अनुसंधान फाउंडेशन की स्थापना।",
        "more_info": "अधिक विस्तृत जानकारी के लिए, कृपया शिक्षा मंत्रालय की आधिकारिक वेबसाइट पर जाएं:",
        "official_nep2020_link": "आधिकारिक एनईपी 2020 लिंक",
        // Hobby page
        "hobby_suggestions_heading": "शौक से करियर के सुझाव",
        "hobby_page_intro": "अपने जुनून के साथ संरेखित करियर पथों की खोज करें!",
        // Exams page
        "key_entrance_exams_heading": "मुख्य प्रवेश परीक्षाएँ",
        "exams_page_intro": "विभिन्न धाराओं के लिए महत्वपूर्ण प्रवेश परीक्षाएँ खोजें।",
        "filter_by_stream": "स्ट्रीम द्वारा फ़िल्टर करें:",
        "engineering": "इंजीनियरिंग",
        "medical": "चिकित्सा",
        "law": "कानून",
        "arts": "कला",
        "degree": "डिग्री",
        // Dashboard page
        "personal_dashboard_heading": "आपका व्यक्तिगत डैशबोर्ड",
        "dashboard_page_intro": "आपके व्यक्तिगत करियर अंतर्दृष्टि में आपका स्वागत है!",
        "your_selections": "आपकी पसंद:",
        "preferred_stream": "पसंदीदा स्ट्रीम:",
        "interests": "रुचियां:",
        "clear_my_data": "मेरा डेटा साफ़ करें",
        // Colleges page
        "top_govt_colleges_heading": "शीर्ष सरकारी कॉलेज",
        "colleges_page_intro": "विभिन्न धाराओं के शीर्ष सरकारी कॉलेजों का अन्वेषण करें।",
        // After 10th page
        "subject_choices_10th_heading": "10वीं कक्षा के बाद विषय विकल्प",
        "subject_choices_10th_intro": "10वीं कक्षा के बाद सही स्ट्रीम चुनना आपके करियर पथ के लिए महत्वपूर्ण है। विकल्पों और उनके निहितार्थों का अन्वेषण करें।",
        "science_stream": "विज्ञान स्ट्रीम",
        "science_focus": "फोकस: भौतिकी, रसायन विज्ञान, जीव विज्ञान/गणित",
        "science_careers": "करियर पथ: इंजीनियरिंग, मेडिसिन, रिसर्च, आईटी",
        "science_skills": "मुख्य कौशल: विश्लेषणात्मक सोच, समस्या-समाधान, तार्किक तर्क",
        "commerce_stream": "वाणिज्य स्ट्रीम",
        "commerce_focus": "फोकस: अकाउंटेंसी, बिजनेस स्टडीज, इकोनॉमिक्स, गणित",
        "commerce_careers": "करियर पथ: वित्त, लेखा, व्यवसाय प्रबंधन, विपणन",
        "commerce_skills": "मुख्य कौशल: वित्तीय साक्षरता, संगठनात्मक कौशल, महत्वपूर्ण सोच",
        "arts_humanities_stream": "कला/मानविकी स्ट्रीम",
        "arts_focus": "फोकस: इतिहास, राजनीति विज्ञान, भूगोल, मनोविज्ञान, साहित्य",
        "arts_careers": "करियर पथ: सिविल सेवा, पत्रकारिता, कानून, शिक्षण, डिजाइन",
        "arts_skills": "मुख्य कौशल: संचार, रचनात्मकता, महत्वपूर्ण विश्लेषण, अनुसंधान",
        "explore_polytechnic_courses": "पॉलिटेक्निक पाठ्यक्रमों का अन्वेषण करें",
        "polytechnic_intro": "पॉलिटेक्निक पाठ्यक्रम 10वीं या 12वीं कक्षा के बाद विभिन्न तकनीकी करियर में सीधे प्रवेश के लिए व्यावहारिक प्रशिक्षण प्रदान करते हैं।",
        "diploma_engineering": "इंजीनियरिंग में डिप्लोमा",
        "engineering_fields": "क्षेत्र: मैकेनिकल, सिविल, इलेक्ट्रिकल, कंप्यूटर साइंस, इलेक्ट्रॉनिक्स",
        "engineering_eligibility": "योग्यता: 10वीं पास",
        "engineering_career": "करियर: जूनियर इंजीनियर, तकनीशियन भूमिकाएँ",
        "view_details": "विवरण देखें",
        "diploma_business_admin": "बिजनेस एडमिनिस्ट्रेशन में डिप्लोमा",
        "business_fields": "क्षेत्र: मार्केटिंग, वित्त, मानव संसाधन, संचालन",
        "business_eligibility": "योग्यता: 10वीं/12वीं पास",
        "business_career": "करियर: बिजनेस एनालिस्ट, ऑफिस मैनेजर, मार्केटिंग असिस्टेंट",
        "diploma_hotel_management": "होटल मैनेजमेंट में डिप्लोमा",
        "hotel_fields": "क्षेत्र: खाद्य और पेय, फ्रंट ऑफिस, हाउसकीपिंग, पाक कला",
        "hotel_eligibility": "योग्यता: 10वीं/12वीं पास",
        "hotel_career": "करियर: होटल ऑपरेशंस, शेफ, इवेंट मैनेजमेंट",
        "explore_vocational_courses": "व्यावसायिक पाठ्यक्रमों का अन्वेषण करें",
        "vocational_intro": "व्यावसायिक पाठ्यक्रम विशिष्ट ट्रेडों के लिए व्यावहारिक कौशल प्रदान करते हैं, 10वीं कक्षा के बाद विभिन्न उद्योगों में सीधे प्रवेश की पेशकश करते हैं।",
        "cert_electrician": "इलेक्ट्रीशियन में प्रमाण पत्र",
        "electrician_duration": "अवधि: 1 वर्ष",
        "electrician_eligibility": "योग्यता: 10वीं पास",
        "electrician_career": "करियर: इलेक्ट्रीशियन, इलेक्ट्रिकल तकनीशियन",
        "diploma_nanny_care": "नैनी केयर में डिप्लोमा",
        "nanny_duration": "अवधि: 2 वर्ष",
        "nanny_eligibility": "योग्यता: 10वीं पास",
        "nanny_career": "करियर: नैनी, चाइल्डकैअर प्रोफेशनल",
        "diploma_automobile": "ऑटोमोबाइल में डिप्लोमा",
        "automobile_duration": "अवधि: 2 वर्ष",
        "automobile_eligibility": "योग्यता: 10वीं पास",
        "automobile_career": "करियर: ऑटोमोबाइल तकनीशियन, सर्विस एडवाइजर",
    }
};
